### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ynlx** [wangxiyang2022/DeepFusionMOT#7]
Hello, when I execute python main.py, I get the following error, what should I do to fix it?

Traceback (most recent call last):
  File "main.py", line 147, in <module>
    seq_dets_3D = np.loadtxt(seq_file_3D, delimiter=',')  # load 3D detections, N x 15
  File "/home/miniconda3/envs/dfmot/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/miniconda3/envs/dfmot/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/miniconda3/envs/dfmot/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /media/DeepFusionMOT/datasets/kitti/train/3D_pointrcnn_Car_val\0000.txt not found.

**Comment by chisyliu** [comment]
Hello

I guess you are running the code in Ubuntu, but it seems the author ran the code in windows. Thus the folder path has some difference in ubuntu and windows

You can go to line 17 of file_operation/file.py
Change "position = detections_root + "\\" + detections_file" to "position = detections_root + "/" + detections_file"

**Comment by trThanhnguyen** [comment]
Actually there are many of works need to be done for completely changing the paths from MS-DOS (Windows) to Unix.
You can refer to this helpful docs and resolve them on the go, re-run each time.
https://www.pythoncheatsheet.org/cheatsheet/file-directory-path#creating-new-folders
Hope this help.
